# Smithery deployment configuration for PsiAnimator-MCP
# Simplified for reliable cloud deployment

apiVersion: v1
kind: Service

metadata:
  name: psianimator-mcp
  description: "Quantum Physics Simulation and Animation MCP Server"
  version: "0.1.0"
  
spec:
  # Build configuration
  build:
    dockerfile: "./Dockerfile"
    context: "."

  # Runtime configuration
  runtime:
    # Resource requirements
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    
    # Environment variables
    env:
      - name: "PSIANIMATOR_TRANSPORT"
        value: "stdio"
      - name: "PYTHONUNBUFFERED"
        value: "1"
    
    # Port configuration
    ports:
      - name: "websocket"
        port: 3000
        
  # Service configuration
  service:
    type: "Server"
    
  # Simple deployment
  deployment:
    replicas: 1